### PR TITLE
Update Atomic Access validation rule for  TaskPayloadWorkgroupEXT

### PR DESCRIPTION
**Pull request by pmistryNV**

### CODE REVIEW

**Review by dgkoch — COMMENTED** [review]
Please update the "Last Modified Date" and Revision at the top and changelog at the bottom of the file as well.

**Comment by pmistryNV** [comment]
@dgkoch kindly review

**Review by dgkoch — COMMENTED** [review]
LGTM.

**Comment by pmistryNV** [comment]
@johnkslang kindly merge

**Pull request merged**
