### PR TITLE
Correct ray payload allowed stages

### PR DESCRIPTION
**Pull request by ewerness-nv**

### CODE REVIEW

**Comment by rg3igalia** [comment]
I was trying to find out how and where to submit this and I found your pull request. Thanks! :sweat_smile:

**Comment by dgkoch** [comment]
Approved by Ray Tracing TSG. Please add changelog and update revision and then de-WIP it.

**Comment by ewerness-nv** [comment]
Updated revision number and history - removed WIP.

**Comment by dgkoch** [comment]
LGTM now.

**Pull request merged**
