### PR TITLE
Add new execution mode to SPV_INTEL_kernel_attributes

### PR DESCRIPTION
**Pull request by tiwaria1**
FPGA kernels can have two types of interfaces - streaming based or register based. This PR adds a new execution mode (`RegisterMapInterfaceINTEL`) which specifies a 'register' based interface. 

`RegisterMapInterfaceINTEL` is being added to the existing `SPV_INTEL_kernel_attributes` extension as this extension already has the other execution mode (`StreamingInterfaceINTEL`) that represents the streaming based interface. We want to keep these two related modes together in one extension document.

To allow backwards compatibility, the new mode is guarded by a new capability `FPGAKernelAttributesv2INTEL`.

### CODE REVIEW

**Comment by tiwaria1** [comment]
The html file was updated using the VSCode AsciiDoc extension.

**Comment by tiwaria1** [comment]
Please take a look, @johnkslang / @alan-baker , thank you!

**Comment by tiwaria1** [comment]
> Can you please add a link to this extension in the README also?

The readme already seems to have this extension linked since it's an existing extension.

**Comment by tiwaria1** [comment]
ping @bashbaug , @johnkslang (I am unable add you as git reviewers)

**Review by bashbaug — COMMENTED** [review]
> The readme already seems to have this extension linked since it's an existing extension.

Whoops, I'd missed that, sorry!

LGTM, needs a non-Intel reviewer before merging.

**Comment by tiwaria1** [comment]
ping @johnkslang / @dneto0 / @alan-baker for review. Thank you!

**Pull request merged**
