### PR TITLE
add SPV_HUAWEI_subpass_shading extension

### PR DESCRIPTION
**Pull request by WyvernWang**

### CODE REVIEW

**Comment by johnkslang** [comment]
Also add it to the bottom of the list of extensions in the README.

**Comment by johnkslang** [comment]
I think the new enumerants still need to be reserved first.

**Comment by johnkslang** [comment]
See include/spirv/spir-v.xml.

**Comment by WyvernWang** [comment]
@raunraun, I've fixed the enum, please check and help to merge, thanks

**Pull request merged**
