### PR TITLE
Fix build failure for QCOM extensions

### PR DESCRIPTION
**Pull request by dgkoch**
Includes fixes from #294 (to be able to test CI)

### CODE REVIEW

**Comment by bashbaug** [comment]
Hmm, seems like the automated builds are always pulling from the main branch, even for PRs.  I see:

```sh
Checking out the ref
  /usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
  Switched to a new branch 'main'
  branch 'main' set up to track 'origin/main'.
/usr/bin/git log -1 --format='%H'
'd33d158f9df194a004c5104ce89699fedf78cf1f'
```

**Comment by dgkoch** [comment]
> Hmm, seems like the automated builds are always pulling from the main branch, even for PRs. I see:

Yes - I noticed that on the last PR as well. I haven't been able to figure out why yet.. (and I've been comparing vs other repos that I know work correctly). 

 Maybe @llvm-beanz  knows?

**Comment by bashbaug** [comment]
Have a look at https://github.com/KhronosGroup/SPIRV-Registry/pull/296 - it changes the automated builds slightly and appears to be building from the correct branch now, and includes these asciidoc fixes.

**Comment by dgkoch** [comment]
> Have a look at #296 - it changes the automated builds slightly and appears to be building from the correct branch now, and includes these asciidoc fixes.

Well it appears to work correctly. I don't understand what is substantively different about it though...

**Comment by Naghasan** [comment]
Closing as it is superseded by https://github.com/KhronosGroup/SPIRV-Registry/pull/296

**Pull request closed without merging**
