### PR TITLE
asciidoc fixes for Intel extensions

### PR DESCRIPTION
**Pull request by bashbaug**
Fixes minor errors in the asciidoc source for the Intel SPIR-V extensions.

I haven't re-generated HTML files with these fixes to keep the diff manageable, but I did verify that all of the extensions build cleanly with the latest spec toolchain now (via `make docker-all`).

### CODE REVIEW

**Comment by bashbaug** [comment]
I found and fixed a few more issues that weren't syntax errors but that did cause the HTML specs to be rendered improperly.

I also added the HTML artifacts, as we discussed.

**Comment by bashbaug** [comment]
@MrSidims and maybe @gmlueck or @PawelJurek, would you mind giving these changes a quick review?  I'd recommend flipping through the rendered HTML to see if anything looks amiss vs. looking at GitHub diffs.  Thanks!

**Comment by MrSidims** [comment]
Went through SPV_INTEL_cache_controls, SPV_INTEL_device_side_avc_motion_estimation, SPV_INTEL_fpga_argument_interfaces and SPV_INTEL_long_composites that present in the PR:
- SPV_INTEL_cache_controls: seems fine
- SPV_INTEL_device_side_avc_motion_estimation:
a. comparing instructions definitions with unified spec, see https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpTypeSampler - there the lowest row of the table is grey, while in https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/bc1fea35f94c75b2d203871b1fea71a4e0d77e1d/extensions/INTEL/SPV_INTEL_device_side_avc_motion_estimation.html#_new_types is white, not sure if it's counts as an issue;
b. the lowest row in type declaration instructions is disjoint from the main table, it doesn't happen for other instructions (compare `OpTypeSampler` from core and the extension);
- SPV_INTEL_fpga_argument_interfaces: seems fine, unrelated to rendering comment, see [Contributors](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/bc1fea35f94c75b2d203871b1fea71a4e0d77e1d/extensions/INTEL/SPV_INTEL_fpga_argument_interfaces.html#_contributors) and [Version](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/bc1fea35f94c75b2d203871b1fea71a4e0d77e1d/extensions/INTEL/SPV_INTEL_fpga_argument_interfaces.html#_version) - they are misaligned with other specifications. Also [Status](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/bc1fea35f94c75b2d203871b1fea71a4e0d77e1d/extensions/INTEL/SPV_INTEL_fpga_argument_interfaces.html#_status) is odd. Guess it should be fixed in other PR.
- SPV_INTEL_long_composites: like in SPV_INTEL_device_side_avc_motion_estimation the type declaration instruction's lowest row is not grey, but white. Not sure if it should be fixed.

**Comment by MrSidims** [comment]
Went through remaining extensions, everything is fine, there are few issues with 'contributors', 'version' and 'status' like in SPV_INTEL_fpga_argument_interfaces, but they are unrelated to the rendering. Also [OpArbitraryFloatSqrtINTEL](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/bc1fea35f94c75b2d203871b1fea71a4e0d77e1d/extensions/INTEL/SPV_INTEL_arbitrary_precision_floating_point.html) has typo in result type, which is also unrelated to rendering.

**Review by MrSidims — APPROVED** [review]

**Comment by bashbaug** [comment]
Thanks for the very thorough review!

The shading is a difference between the core spec toolchain and the extension toolchain.  I filed an issue to discuss.

I fixed the result type typo for OpArbitraryFloatSqrtINTEL.

I think I'll save the others for another PR though.

**Comment by bashbaug** [comment]
Merging as discussed in the August 28th teleconference.

**Pull request merged**
